### ISSUE TITLE
Different logo-size for iStick Pico

### ISSUE THREAD

**Issue by Musik234** [Ban3/python-evic#15]
Eleaf released firmware version 1.01 for the iStick Pico today.
Now you can upload a logo with the dimensions 96x16px.
"evic-usb upload-logo" shows the following errormessage:

`$ evic-usb upload-logo musik234-96x16.bmp 

Finding device...OK
    Manufacturer: Joyetech
    Product: HID Transfer
    Serial No: A02014090304

Reading data flash...OK
    Device name: iStick Pico
    Firmware version: 0.00
    Hardware version: 1.00

Image dimensions must be 64x40.
Writing logo...Traceback (most recent call last):
  File "/usr/local/bin/evic-usb", line 9, in <module>
    load_entry_point('evic==0.1', 'console_scripts', 'evic-usb')()
  File "/usr/local/lib/python2.7/dist-packages/click-6.2-py2.7.egg/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.2-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.2-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-6.2-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "build/bdist.linux-x86_64/egg/evic/cli.py", line 290, in uploadlogo
UnboundLocalError: local variable 'logo' referenced before assignment
`

**Comment by ReservedField** [comment]
I took a look at the Pico updater and jotted down a fix on my `pico-logo-fix` branch, please try it out:

```
git remote add ReservedField https://github.com/ReservedField/python-evic
git remote update
git pull ReservedField pico-logo-fix
git checkout pico-logo-fix
(sudo) python setup.py install
```

I haven't really tested it, but it should work. They use the same algo, I just had to allow arbitrary sizes.

**Comment by Musik234** [comment]
Ughs, I didn't hear the thunder, but you were fast as lightning. ;-)

It works.
Thanks a lot.

**Comment by ReservedField** [comment]
Great.
@Ban3 I would PR this, but we should probably check the permitted logo sizes for each device. Don't know what's the cleanest way to do it. Maybe check in `HIDTransfer.write_logo`?
