### ISSUE TITLE
Wismec Presa TC75W Test Results

### ISSUE THREAD

**Issue by AndydeCleyre** [Ban3/python-evic#34]
Thanks!

I'm on Arch Linux and installed via the `python-evic-git` PKGBUILD in the AUR.

Plugged in, ran `evic-usb dump-dataflash -o out.bin`:

```
Finding device...OK
        Manufacturer: Nuvoton
        Product: HID Transfer
        Serial No: A02014090304

Reading data flash...OK
        Device name: Presa TC75W
        Firmware version: 3.00
        Hardware version: 1.01

Writing data flash to the file...OK
```

Success!

Ran `evic-usb upload Presa_TC75W_V4.03.bin`:

```
Finding device...OK
        Manufacturer: Nuvoton
        Product: HID Transfer
        Serial No: A02014090304

Reading data flash...OK
Verifying data flash...OK
        Device name: Presa TC75W
        Firmware version: 3.00
        Hardware version: 1.01

Verifying APROM...OK
Writing data flash...OK
Restarting the device...OK
Finding device...OK
Writing APROM...OK
```

Success!

The screen on the device seemed distorted, but that may just be the new style. I tried `evic-usb screenshot -o screenshot.png`, but it just hung after

```
Finding device...OK
```

![20170226_184440](https://cloud.githubusercontent.com/assets/1787385/23344972/fb4c51ec-fc53-11e6-811f-853c1064a73a.jpg)

Thanks again for enabling me to easily flash this without Windows!

**Comment by ghost** [comment]
How did you do that? I've got following error while trying to dump flash using latest master:
```
Finding device...Traceback (most recent call last):
  File "/home/god/.local/bin/evic-usb", line 11, in <module>
    sys.exit(usb())
  File "/home/god/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/god/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/god/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/god/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/god/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/god/.local/lib/python3.6/site-packages/evic/cli.py", line 320, in dumpdataflash
    connect(dev)
  File "/home/god/.local/lib/python3.6/site-packages/evic/cli.py", line 67, in connect
    dev.connect()
  File "/home/god/.local/lib/python3.6/site-packages/evic/device.py", line 121, in connect
    self.device.open(self.vid, self.pid)
AttributeError: 'NoneType' object has no attribute 'open'
```

**Comment by artisan-digital** [comment]
I experienced the same.  The python-evic cli.py and device.py code does not conform to the current python hid interface, hence the attribute error.  It could be that the current master was intended for a different version of hid, but I haven't verified that. 

This fork of Ban3/python-evic contains the necessary fixes to get you up and running:
https://github.com/artisan-digital/python-evic
